name: Manually demote a user
on:
  issues:
    types: [closed]

jobs:
  manual-demote-workflow:
    name: Demoting a user for closing an issue
    runs-on: ubuntu-latest
    env:
      DEMOTION_ERROR_NOTIFY: '@team'
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automation-running

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # This token is required push changes later
          token: ${{ secrets.PAT }}

      - name: Parse the issue submitted
        id: issue_parser
        uses: ./admin-support-cli
        with:
          action: "parse_issue"
          issue_number: ${{ github.event.issue.number }}

      - name: Parse issue_parser json output
        id: parse_issue_output
        run: |
          TARGET_ORG=$(echo ${{toJSON(steps.issue_parser.outputs.output)}} | jq -r .target_org)
          DESCRIPTION=$(echo ${{toJSON(steps.issue_parser.outputs.output)}} | jq -r .description)
          DURATION=$(echo ${{toJSON(steps.issue_parser.outputs.output)}} | jq -r .duration)
          TICKET=$(echo ${{toJSON(steps.issue_parser.outputs.output)}} | jq -r .ticket)
          echo "::set-output name=target_org::$TARGET_ORG"
          echo "::set-output name=description::$DESCRIPTION"
          echo "::set-output name=duration::$DURATION"
          echo "::set-output name=ticket::$TICKET"

      - name: Demote user
        id: demote_admin
        uses: ./admin-support-cli
        continue-on-error: true
        with:
          action: "promote_demote"
          username: ${{ github.event.issue.user.login }}
          target_org: ${{ steps.parse_issue_output.outputs.target_org }}
          role: 'member'
          admin_token: ${{ secrets.PAT }}

      - name: Set demotion date after user has been demoted
        id: create_demotion_date
        run: |
           DEMOTION_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
           echo "::set-output name=demotion_date::$DEMOTION_DATE"

      - name: Create reports folder if does not exist
        run: |
          mkdir -p reports
          ls -Fla

      - name: Sleep to allow audit logs to catch up
        run: |
          sleep 30

      - name: Report admin operations
        id: report_admin_ops
        uses: ./admin-support-cli
        continue-on-error: true
        with:
          action: "demotion_report"
          username: ${{ github.event.issue.user.login }}
          description: ${{ steps.parse_issue_output.outputs.description }}
          issue_number:  ${{ github.event.issue.number }}
          duration: ${{ steps.parse_issue_output.outputs.duration }}
          ticket: ${{ steps.parse_issue_output.outputs.ticket }}
          demotion_date: ${{ steps.create_demotion_date.outputs.demotion_date }}
          promotion_date: ${{ github.event.issue.created_at }}
          target_org: ${{ steps.parse_issue_output.outputs.target_org }}
          admin_token: ${{ secrets.PAT }}

      - name: Persist the audit of the demotion
        uses: EndBug/add-and-commit@v7
        with:
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          message: "Adding report for issue #${{ github.event.issue.number }} for ${{ github.event.issue.user.login }} demotion"
          push: true

      - name: Add a comment on the issue to confirm the demotion
        uses: actions/github-script@v6
        if: success()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ &nbsp; We have executed the request and now the user **@${{github.event.issue.user.login}}** has been demoted from ${{steps.parse_issue_output.outputs.target_org}}. \n\n This issue will be locked to avoid new interactions

              <sub>
                Find details of the automation <a href="https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${{github.run_id}}">here</a>.
              </sub>
              `
            })
            await github.rest.issues.lock({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo
            })

      - name: Add a comment to notify the team that this automation failed
        uses: actions/github-script@v6
        if: failure()
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Demoting the user has failed. ${{env.DEMOTION_ERROR_NOTIFY}} have a look to make sure the user is left in a correct state.

              <sub>
                Find details of the automation <a href="https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${{github.run_id}}">here</a>.
              </sub>
              `
            })

      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ success() && github.event.sender.login == github.event.issue.user.login }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            manual-demotion
            user-demoted

      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{ success() && github.event.sender.login != github.event.issue.user.login }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            automatic-demotion
            user-demoted

      - uses: actions-ecosystem/action-remove-labels@v1
        if: success()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: user-promoted

      - uses: actions-ecosystem/action-remove-labels@v1
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: automation-running
